# https://gohugo.io/

# https://bearblog.dev/
theme = 'hugo-bearblog'
baseURL = "https://kaj.gay"
title = "Kaj Strife"
author = "Kaj Strife"
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  description = "The website of Kaj Strife"
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "Kaj Strife"
  hideMadeWithLine = true
  dateFormat = "2006-01-02"
